Repository boostcamp-ai-tech-4/coding-test-study, pull requests merged in 2021-06, with the labels that each got.

#63 [샐리] 2021.06.09
  sally/README.md
  sally/string/17413_단어 뒤집기 2.cpp
  sally/string/17609_회문.cpp
Labels: adc, humi, penguin, 👀 not yet

#65 [원딜] 2021.06.09
  changwoomon/string/17413_단어뒤집기2.py
  changwoomon/string/17609_회문.py
Labels: guneo, humi, penguin, 👀 not yet

#73 [구너] 2021.06.11
  osmosm7/Tree/11725_트리의부모찾기.py
  osmosm7/Tree/9934_완전이진트리.py
Labels: humi, 👀 not yet

#74 [샐리] 2021.06.11
  sally/README.md
  sally/tree/11725_트리의 부모 찾기.cpp
  sally/tree/9934_완전 이진 트리.cpp
Labels: humi, 👀 not yet

#75 [펭귄] 2021.06.11
  coodingpenguin/README.md
  coodingpenguin/tree/11725_트리의부모찾기.py
  coodingpenguin/tree/9934_완전이진트리.py
Labels: guneo, humi, 👀 not yet

#76 [튜브] 2020.06.11
  peacecheejecake/README.md
  peacecheejecake/tree/11725_트리의부모찾기.py
  peacecheejecake/tree/9934_OBILAZAK.py
Labels: humi, sally, 👀 not yet

#77 [원딜] 2021.06.14
  changwoomon/tree/1991_트리순회.py
  changwoomon/tree/5639_이진검색트리.py
Labels: guneo, humi, penguin, tube, 👀 not yet

#78 [구너] 2021.06.15
  osmosm7/Tree/1068_트리.py
Labels: adc, humi, sally, 👀 not yet

#79 [샐리] 2021.06.15
  sally/README.md
  sally/tree/1068_트리.cpp
Labels: adc, guneo, humi, 👀 not yet

#80 [튜브] 2021.06.15
  peacecheejecake/README.md
  peacecheejecake/tree/1068_트리.py
Labels: adc, guneo, humi, sally, 👀 not yet

#81 [펭귄] 2021.06.15
  coodingpenguin/README.md
  coodingpenguin/tree/1068_트리.py
Labels: adc, guneo, humi, sally, 👀 not yet

#82 [후미] 2021.06.16
  opijae/tree/14675_단절점과단절선.py
Labels: adc, guneo, sally, tube, 👀 not yet

#83 [튜브] 2021.06.16
  peacecheejecake/README.md
  peacecheejecake/tree/6416_트리인가.py
Labels: adc, guneo, sally, 👀 not yet

#84 [펭귄] 2021.06.16
  coodingpenguin/README.md
  coodingpenguin/tree/6416_트리인가.py
Labels: adc, guneo, humi, sally, 👀 not yet

#85 [샐리] 2021.06.16
  sally/README.md
  sally/tree/6416_트리인가.cpp
Labels: adc, guneo, humi, tube, 👀 not yet

#95 [펭귄] 2021.06.18
  coodingpenguin/README.md
  coodingpenguin/tree/17073_나무위의빗물_1.py
  coodingpenguin/tree/17073_나무위의빗물_2.py
  coodingpenguin/tree/17073_나무위의빗물_3.py
Labels: humi, sally, tube, 👀 not yet

#97 [원딜] 2021.06.15
  changwoomon/tree/1068_트리.py
Labels: humi, sally, tube, 👀 not yet
